export default {
  title: 'light',

  colors: {
    // primary: '#EFEFEF',
    primary: '#F3F8EC',
    secondary: '#F3F8EC',
    text: '#353535',
    border: '#000',
    borderInput: '#CCCCCC',
    backgroundInput: '#E5E5E5',
    grayButton: '#E5E5E5',
    shadowMobile: '#E5E5E5',
    shadowCards: '#AAAAAA',
    backgroundMouseOver: ' #DAE8C3',
    backgroundDiv: '#CCCCCC',
    divCounter: '#E5E5E5',
    backgroundHtml: 'rgb(243,248,236)',
    colorStatusGreen: '#3fb950',
    colorStatusYellow: ' #cf8d2e',

    white: '#fff',
    background: '#f2f3f5',
    text_highlight: '#ADADAD',
    title: '#2E384D',
    red: '#ADADAD',
    green: '#3fb950',
    blue: '#5965E0',
    blue_dark: '#4953B8',
    blue_twitter: '#2AA9E0',
    black: '#fff',
  },
};
